/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uKontroler;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.zip.Adler32;
import java.util.zip.CheckedInputStream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author wojtek
 */
public class Eeprom extends javax.swing.JDialog {

  /**
   * Creates new form Eeprom
   */
  int dialX = 0;
  int dialY = 0;
  JFrame frame;
  public static Object[][] data;
  public static String[][] akxKom;
  Color color = new Color(238, 238, 238);
  Object options[] = {"Tak", "Nie"};
  public static int[][][] sekwencje = new int[7][4][8];
  public static String[][] sekwT = new String[4][8];
  public static Object[][] rx;
  public static Object[][] zewx;
  public static Object[][] ix;
  public static Object[][] sterow0;
  public static Object[][] sterow12;
  public static Object[][] param;
  public static Object[][] charakt;
  int odplyw = 0;
  public static boolean ustaw = false;
  public Eeprom(JFrame frame, boolean modal) {
    super(frame, modal);
    this.frame = frame;
//    frame.setEnabled(!modal);
    initComponents();

    uzupelnij();
  }

  public Eeprom() {
    super();
    initComponents();
  }

  private void uzupelnij() {
    if (!ustaw) {
      ustaw = true;
      for (int i = 0; i < 7; i++) {
        for (int j = 0; j < 4; j++) {
          for (int k = 0; k < 8; k++) {
            sekwencje[i][j][k] = 0;
          }
        }
      }
      for (int i = 0; i < 4; i++) {
        for (int k = 0; k < 8; k++) {
          sekwT[i][k] = "00.00";
        }
      }
    }

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Rectangle rect = new Rectangle();
    int przesX = 150;
    int przesY = 100;
    dialX = screenSize.width - 2 * przesX;
    dialY = screenSize.height - 2 * przesY;
    rect.setBounds(przesX, przesY, dialX, dialY);
    this.setBounds(rect);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jButton8 = new javax.swing.JButton();
    jPanel6 = new javax.swing.JPanel();
    jButton16 = new javax.swing.JButton();
    jButton17 = new javax.swing.JButton();
    jButton18 = new javax.swing.JButton();
    jButton19 = new javax.swing.JButton();
    jPanel7 = new javax.swing.JPanel();
    jButton24 = new javax.swing.JButton();
    jButton25 = new javax.swing.JButton();
    jButton26 = new javax.swing.JButton();
    jButton27 = new javax.swing.JButton();
    jPanel8 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel9 = new javax.swing.JPanel();
    jPanel16 = new javax.swing.JPanel();
    jButton33 = new javax.swing.JButton();
    jButton32 = new javax.swing.JButton();
    jComboBox3 = new javax.swing.JComboBox<>();
    jPanel4 = new javax.swing.JPanel();
    jPanel10 = new javax.swing.JPanel();
    jButton9 = new javax.swing.JButton();
    jButton10 = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();
    jButton12 = new javax.swing.JButton();
    jButton13 = new javax.swing.JButton();
    jButton14 = new javax.swing.JButton();
    jButton15 = new javax.swing.JButton();
    jPanel11 = new javax.swing.JPanel();
    jButton20 = new javax.swing.JButton();
    jButton21 = new javax.swing.JButton();
    jButton22 = new javax.swing.JButton();
    jButton23 = new javax.swing.JButton();
    jPanel12 = new javax.swing.JPanel();
    jButton28 = new javax.swing.JButton();
    jButton29 = new javax.swing.JButton();
    jButton30 = new javax.swing.JButton();
    jButton31 = new javax.swing.JButton();
    jPanel13 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jPanel17 = new javax.swing.JPanel();
    jPanel19 = new javax.swing.JPanel();
    jButton34 = new javax.swing.JButton();
    jButton35 = new javax.swing.JButton();
    jComboBox6 = new javax.swing.JComboBox<>();
    jPanel2 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1,
    javax.swing.BoxLayout.LINE_AXIS));

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
    "Odp³yw 1", javax.swing.border.TitledBorder.CENTER,
    javax.swing.border.TitledBorder.DEFAULT_POSITION,
    new java.awt.Font("Tahoma", 1, 11))); // NOI18N
    jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3,
    javax.swing.BoxLayout.Y_AXIS));

    jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel5.setPreferredSize(new java.awt.Dimension(265, 50));
    java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
    flowLayout1.setAlignOnBaseline(true);
    jPanel5.setLayout(flowLayout1);

    jButton2.setText("<html>AK5<html>\n");
    jButton2.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton2MouseClicked(evt);
      }

    });
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }

    });
    jPanel5.add(jButton2);

    jButton3.setText("<html>AK6<html>");
    jButton3.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton3MouseClicked(evt);
      }

    });
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }

    });
    jPanel5.add(jButton3);

    jButton4.setText("<html>AK7<html>");
    jButton4.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton4MouseClicked(evt);
      }

    });
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }

    });
    jPanel5.add(jButton4);

    jButton5.setText("<html>AK1<html>");
    jButton5.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton5MouseClicked(evt);
      }

    });
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }

    });
    jPanel5.add(jButton5);

    jButton6.setText("<html>AK2<html>");
    jButton6.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton6MouseClicked(evt);
      }

    });
    jButton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton6ActionPerformed(evt);
      }

    });
    jPanel5.add(jButton6);

    jButton7.setText("<html>AK3<html>");
    jButton7.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton7MouseClicked(evt);
      }

    });
    jButton7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton7ActionPerformed(evt);
      }

    });
    jPanel5.add(jButton7);

    jButton8.setText("<html>AK4<html>");
    jButton8.setFocusable(false);
    jButton8.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton8MouseClicked(evt);
      }

    });
    jButton8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton8ActionPerformed(evt);
      }

    });
    jPanel5.add(jButton8);

    jPanel3.add(jPanel5);

    jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel6.setPreferredSize(new java.awt.Dimension(265, 50));
    java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout();
    flowLayout3.setAlignOnBaseline(true);
    jPanel6.setLayout(flowLayout3);

    jButton16.setText("R1");
    jButton16.setPreferredSize(new java.awt.Dimension(51, 51));
    jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton16MouseClicked(evt);
      }

    });
    jButton16.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton16ActionPerformed(evt);
      }

    });
    jPanel6.add(jButton16);

    jButton17.setText("R2");
    jButton17.setPreferredSize(new java.awt.Dimension(51, 51));
    jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton17MouseClicked(evt);
      }

    });
    jButton17.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton17ActionPerformed(evt);
      }

    });
    jPanel6.add(jButton17);

    jButton18.setText("R3");
    jButton18.setPreferredSize(new java.awt.Dimension(51, 51));
    jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton18MouseClicked(evt);
      }

    });
    jButton18.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton18ActionPerformed(evt);
      }

    });
    jPanel6.add(jButton18);

    jButton19.setText("R4");
    jButton19.setPreferredSize(new java.awt.Dimension(51, 51));
    jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton19MouseClicked(evt);
      }

    });
    jButton19.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton19ActionPerformed(evt);
      }

    });
    jPanel6.add(jButton19);

    jPanel3.add(jPanel6);

    jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel7.setPreferredSize(new java.awt.Dimension(265, 50));
    java.awt.FlowLayout flowLayout5 = new java.awt.FlowLayout();
    flowLayout5.setAlignOnBaseline(true);
    jPanel7.setLayout(flowLayout5);

    jButton24.setText("ZEW1");
    jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton24MouseClicked(evt);
      }

    });
    jButton24.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton24ActionPerformed(evt);
      }

    });
    jPanel7.add(jButton24);

    jButton25.setText("ZEW2");
    jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton25MouseClicked(evt);
      }

    });
    jButton25.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton25ActionPerformed(evt);
      }

    });
    jPanel7.add(jButton25);

    jButton26.setText("ZEW3");
    jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton26MouseClicked(evt);
      }

    });
    jButton26.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton26ActionPerformed(evt);
      }

    });
    jPanel7.add(jButton26);

    jButton27.setText("ZEW4");
    jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton27MouseClicked(evt);
      }

    });
    jButton27.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton27ActionPerformed(evt);
      }

    });
    jPanel7.add(jButton27);

    jPanel3.add(jPanel7);

    jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel8.setPreferredSize(new java.awt.Dimension(265, 50));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setText("I1");
    jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(
    javax.swing.border.BevelBorder.RAISED));
    jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
    jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel1MouseClicked(evt);
      }

    });

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
    jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 494, Short.MAX_VALUE)
    .addGroup(jPanel8Layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel8Layout.createSequentialGroup()
    .addGap(0, 0, Short.MAX_VALUE)
    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).
    addGap(0, 0, Short.MAX_VALUE)))
    );
    jPanel8Layout.setVerticalGroup(
    jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 44, Short.MAX_VALUE)
    .addGroup(jPanel8Layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel8Layout.createSequentialGroup()
    .addGap(0, 0, Short.MAX_VALUE)
    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).
    addGap(0, 0, Short.MAX_VALUE)))
    );

    jPanel3.add(jPanel8);

    jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel9.setPreferredSize(new java.awt.Dimension(265, 50));
    jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9,
    javax.swing.BoxLayout.Y_AXIS));

    java.awt.FlowLayout flowLayout7 = new java.awt.FlowLayout();
    flowLayout7.setAlignOnBaseline(true);
    jPanel16.setLayout(flowLayout7);

    jButton33.setText("Sterowania");
    jButton33.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton33ActionPerformed(evt);
      }

    });
    jPanel16.add(jButton33);

    jButton32.setText("Sekwencje");
    jButton32.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton32ActionPerformed(evt);
      }

    });
    jPanel16.add(jButton32);

    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
      "Parametry", "Charakterystyki"}));
    jComboBox3.setBorder(javax.swing.BorderFactory.createTitledBorder(
    "Model cieplny"));
    jComboBox3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox3ActionPerformed(evt);
      }

    });
    jPanel16.add(jComboBox3);

    jPanel9.add(jPanel16);

    jPanel3.add(jPanel9);

    jPanel1.add(jPanel3);

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
    "Odp³yw 2", javax.swing.border.TitledBorder.CENTER,
    javax.swing.border.TitledBorder.DEFAULT_POSITION,
    new java.awt.Font("Tahoma", 1, 11))); // NOI18N
    jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4,
    javax.swing.BoxLayout.Y_AXIS));

    jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel10.setPreferredSize(new java.awt.Dimension(265, 50));
    java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout();
    flowLayout2.setAlignOnBaseline(true);
    jPanel10.setLayout(flowLayout2);

    jButton9.setText("<html>AK5<html>");
    jButton9.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton9MouseClicked(evt);
      }

    });
    jButton9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton9ActionPerformed(evt);
      }

    });
    jPanel10.add(jButton9);

    jButton10.setText("<html>AK6<html>");
    jButton10.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton10MouseClicked(evt);
      }

    });
    jButton10.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton10ActionPerformed(evt);
      }

    });
    jPanel10.add(jButton10);

    jButton11.setText("<html>AK7<html>");
    jButton11.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton11MouseClicked(evt);
      }

    });
    jButton11.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton11ActionPerformed(evt);
      }

    });
    jPanel10.add(jButton11);

    jButton12.setText("<html>AK1<html>");
    jButton12.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton12MouseClicked(evt);
      }

    });
    jButton12.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton12ActionPerformed(evt);
      }

    });
    jPanel10.add(jButton12);

    jButton13.setText("<html>AK2<html>");
    jButton13.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton13MouseClicked(evt);
      }

    });
    jButton13.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton13ActionPerformed(evt);
      }

    });
    jPanel10.add(jButton13);

    jButton14.setText("<html>AK3<html>");
    jButton14.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton14MouseClicked(evt);
      }

    });
    jButton14.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton14ActionPerformed(evt);
      }

    });
    jPanel10.add(jButton14);

    jButton15.setText("<html>AK4<html>");
    jButton15.setPreferredSize(new java.awt.Dimension(51, 60));
    jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton15MouseClicked(evt);
      }

    });
    jButton15.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton15ActionPerformed(evt);
      }

    });
    jPanel10.add(jButton15);

    jPanel4.add(jPanel10);

    jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel11.setPreferredSize(new java.awt.Dimension(265, 50));
    java.awt.FlowLayout flowLayout4 = new java.awt.FlowLayout();
    flowLayout4.setAlignOnBaseline(true);
    jPanel11.setLayout(flowLayout4);

    jButton20.setText("R1");
    jButton20.setPreferredSize(new java.awt.Dimension(51, 51));
    jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton20MouseClicked(evt);
      }

    });
    jButton20.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton20ActionPerformed(evt);
      }

    });
    jPanel11.add(jButton20);

    jButton21.setText("R2");
    jButton21.setPreferredSize(new java.awt.Dimension(51, 51));
    jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton21MouseClicked(evt);
      }

    });
    jButton21.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton21ActionPerformed(evt);
      }

    });
    jPanel11.add(jButton21);

    jButton22.setText("R3");
    jButton22.setPreferredSize(new java.awt.Dimension(51, 51));
    jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton22MouseClicked(evt);
      }

    });
    jButton22.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton22ActionPerformed(evt);
      }

    });
    jPanel11.add(jButton22);

    jButton23.setText("R4");
    jButton23.setPreferredSize(new java.awt.Dimension(51, 51));
    jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton23MouseClicked(evt);
      }

    });
    jButton23.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton23ActionPerformed(evt);
      }

    });
    jPanel11.add(jButton23);

    jPanel4.add(jPanel11);

    jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel12.setPreferredSize(new java.awt.Dimension(265, 50));
    java.awt.FlowLayout flowLayout6 = new java.awt.FlowLayout();
    flowLayout6.setAlignOnBaseline(true);
    jPanel12.setLayout(flowLayout6);

    jButton28.setText("ZEW1");
    jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton28MouseClicked(evt);
      }

    });
    jButton28.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton28ActionPerformed(evt);
      }

    });
    jPanel12.add(jButton28);

    jButton29.setText("ZEW2");
    jButton29.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton29MouseClicked(evt);
      }

    });
    jButton29.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton29ActionPerformed(evt);
      }

    });
    jPanel12.add(jButton29);

    jButton30.setText("ZEW3");
    jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton30MouseClicked(evt);
      }

    });
    jButton30.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton30ActionPerformed(evt);
      }

    });
    jPanel12.add(jButton30);

    jButton31.setText("ZEW4");
    jButton31.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton31MouseClicked(evt);
      }

    });
    jButton31.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton31ActionPerformed(evt);
      }

    });
    jPanel12.add(jButton31);

    jPanel4.add(jPanel12);

    jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel13.setPreferredSize(new java.awt.Dimension(265, 50));

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel2.setText("I2");
    jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(
    javax.swing.border.BevelBorder.RAISED));
    jLabel2.setPreferredSize(new java.awt.Dimension(30, 30));
    jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel2MouseClicked(evt);
      }

    });

    javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(
    jPanel13);
    jPanel13.setLayout(jPanel13Layout);
    jPanel13Layout.setHorizontalGroup(
    jPanel13Layout.
    createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 0, Short.MAX_VALUE)
    .addGroup(jPanel13Layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel13Layout.createSequentialGroup()
    .addGap(0, 0, Short.MAX_VALUE)
    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).
    addGap(0, 0, Short.MAX_VALUE)))
    );
    jPanel13Layout.setVerticalGroup(
    jPanel13Layout.
    createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 45, Short.MAX_VALUE)
    .addGroup(jPanel13Layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel13Layout.createSequentialGroup()
    .addGap(0, 0, Short.MAX_VALUE)
    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).
    addGap(0, 0, Short.MAX_VALUE)))
    );

    jPanel4.add(jPanel13);

    jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));
    jPanel17.setPreferredSize(new java.awt.Dimension(265, 50));
    jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17,
    javax.swing.BoxLayout.Y_AXIS));

    java.awt.FlowLayout flowLayout9 = new java.awt.FlowLayout();
    flowLayout9.setAlignOnBaseline(true);
    jPanel19.setLayout(flowLayout9);

    jButton34.setText("Sterowania");
    jButton34.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton34ActionPerformed(evt);
      }

    });
    jPanel19.add(jButton34);

    jButton35.setText("Sekwencje");
    jButton35.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton35ActionPerformed(evt);
      }

    });
    jPanel19.add(jButton35);

    jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
      "Parametry", "Charakterystyki"}));
    jComboBox6.setBorder(javax.swing.BorderFactory.createTitledBorder(
    "Model cieplny"));
    jComboBox6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox6ActionPerformed(evt);
      }

    });
    jPanel19.add(jComboBox6);

    jPanel17.add(jPanel19);

    jPanel4.add(jPanel17);

    jPanel1.add(jPanel4);

    jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(
    new java.awt.Color(0, 0, 0)));

    jButton1.setText("Sterowanie wspólne");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }

    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 0, Short.MAX_VALUE)
    .addGroup(jPanel2Layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel2Layout.createSequentialGroup()
    .addGap(0, 0, Short.MAX_VALUE)
    .addComponent(jButton1)
    .addGap(0, 0, Short.MAX_VALUE)))
    );
    jPanel2Layout.setVerticalGroup(
    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 36, Short.MAX_VALUE)
    .addGroup(jPanel2Layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel2Layout.createSequentialGroup()
    .addGap(0, 5, Short.MAX_VALUE)
    .addComponent(jButton1)
    .addGap(0, 6, Short.MAX_VALUE)))
    );

    jMenu1.setText("Program");

    jMenuItem1.setText("Zapisz");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }

    });
    jMenu1.add(jMenuItem1);

    jMenuItem2.setText("Anuluj");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem2ActionPerformed(evt);
      }

    });
    jMenu1.add(jMenuItem2);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
    getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014,
    Short.MAX_VALUE)
    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap())
    );
    layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 264,
    Short.MAX_VALUE)
    .addGap(18, 18, 18)
    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).
    addGap(24, 24, 24))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
  dispose();
  File file = new File("nastaw.prop");
  file.delete();
//  data = null;
//  frame.setEnabled(true);
//  frame.requestFocus();
  }//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
  dispose();
  File file = new File("nastaw.prop");
  file.delete();
  createBuff();
//  data = null;
//  frame.setEnabled(true);
//  frame.requestFocus();
  }//GEN-LAST:event_jMenuItem1ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  JDialog jfSter = new SterowaniaPp(this, true, 0);
  jfSter.setVisible(true);
  }//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  if (jButton2.getBackground() == Color.red) {
    jButton2.setBackground(color);
    jButton9.setBackground(color);
  } else {
    jButton2.setBackground(Color.red);
    jButton9.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton2ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
  if (jButton9.getBackground() == Color.red) {
    jButton2.setBackground(color);
    jButton9.setBackground(color);
  } else {
    jButton9.setBackground(Color.red);
    jButton2.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton9ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  if (jButton3.getBackground() == Color.red) {
    jButton3.setBackground(color);
    jButton10.setBackground(color);
  } else {
    jButton3.setBackground(Color.red);
    jButton10.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton3ActionPerformed

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
  if (jButton10.getBackground() == Color.red) {
    jButton10.setBackground(color);
    jButton3.setBackground(color);
  } else {
    jButton10.setBackground(Color.red);
    jButton3.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton10ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  if (jButton4.getBackground() == Color.red) {
    jButton4.setBackground(color);
    jButton11.setBackground(color);
  } else {
    jButton4.setBackground(Color.red);
    jButton11.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton4ActionPerformed

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
  if (jButton11.getBackground() == Color.red) {
    jButton11.setBackground(color);
    jButton4.setBackground(color);
  } else {
    jButton11.setBackground(Color.red);
    jButton4.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton11ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  if (jButton5.getBackground() == Color.red) {
    jButton5.setBackground(color);
    jButton12.setBackground(color);
  } else {
    jButton5.setBackground(Color.red);
    jButton12.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton5ActionPerformed

private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
  if (jButton12.getBackground() == Color.red) {
    jButton12.setBackground(color);
    jButton5.setBackground(color);
  } else {
    jButton12.setBackground(Color.red);
    jButton5.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton12ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  if (jButton6.getBackground() == Color.red) {
    jButton6.setBackground(color);
    jButton13.setBackground(color);
  } else {
    jButton6.setBackground(Color.red);
    jButton13.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton6ActionPerformed

private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
  if (jButton13.getBackground() == Color.red) {
    jButton13.setBackground(color);
    jButton6.setBackground(color);
  } else {
    jButton13.setBackground(Color.red);
    jButton6.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton13ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
  if (jButton7.getBackground() == Color.red) {
    jButton7.setBackground(color);
    jButton14.setBackground(color);
  } else {
    jButton7.setBackground(Color.red);
    jButton14.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton7ActionPerformed

private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
  if (jButton14.getBackground() == Color.red) {
    jButton14.setBackground(color);
    jButton7.setBackground(color);
  } else {
    jButton14.setBackground(Color.red);
    jButton7.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton14ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
  if (jButton8.getBackground() == Color.red) {
    jButton8.setBackground(color);
    jButton15.setBackground(color);
  } else {
    jButton8.setBackground(Color.red);
    jButton15.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton8ActionPerformed

private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
  if (jButton15.getBackground() == Color.red) {
    jButton15.setBackground(color);
    jButton8.setBackground(color);
  } else {
    jButton15.setBackground(Color.red);
    jButton8.setBackground(Color.blue);
  }
  }//GEN-LAST:event_jButton15ActionPerformed

private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
  jButton16.setBackground(Color.red);
  jButton20.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton16ActionPerformed

private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
  jButton20.setBackground(Color.red);
  jButton16.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton20ActionPerformed

private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
  jButton17.setBackground(Color.red);
  jButton21.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton17ActionPerformed

private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
  jButton21.setBackground(Color.red);
  jButton17.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton21ActionPerformed

private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
  jButton18.setBackground(Color.red);
  jButton22.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton18ActionPerformed

private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
  jButton22.setBackground(Color.red);
  jButton18.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton22ActionPerformed

private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
  jButton19.setBackground(Color.red);
  jButton23.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton19ActionPerformed

private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
  jButton23.setBackground(Color.red);
  jButton19.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton23ActionPerformed

private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
  jButton24.setBackground(Color.red);
  jButton28.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton24ActionPerformed

private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
  jButton28.setBackground(Color.red);
  jButton24.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton28ActionPerformed

private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
  jButton25.setBackground(Color.red);
  jButton29.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton25ActionPerformed

private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
  jButton29.setBackground(Color.red);
  jButton25.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton29ActionPerformed

private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
  jButton26.setBackground(Color.red);
  jButton30.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton26ActionPerformed

private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
  jButton30.setBackground(Color.red);
  jButton26.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton30ActionPerformed

private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
  jButton27.setBackground(Color.red);
  jButton31.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton27ActionPerformed

private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
  jButton31.setBackground(Color.red);
  jButton27.setBackground(Color.BLUE);
  }//GEN-LAST:event_jButton31ActionPerformed

private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
  int i = jComboBox3.getSelectedIndex();
  JDialog jMC;
  if (i == 0) {
    jMC = new Parametry(this, true, 1);
  } else {
    jMC = new Charakterystyki(this, true, 1);
  }
  jMC.setVisible(true);
  }//GEN-LAST:event_jComboBox3ActionPerformed
  private void ak(String akNr, int odplyw) {
    File f = new File("uKontroler.jar");
    if (!f.exists()) {
      f = new File("dist/uKontroler.jar");
    }
    if (!f.exists()) {
      JOptionPane.showMessageDialog(this, "blad 2");
      System.exit(0);
    }
    if (!odzipuj(f)) {
      JOptionPane.showMessageDialog(this, "blad 3");
      System.exit(0);
    }
    File file = new File("nastaw.prop");
    JDialog akx = new AKx(this, true, file, akNr, Integer.toString(odplyw));
    akx.setVisible(true);
  }
private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
  if (evt.isMetaDown()) {
    if (jButton2.getBackground() == Color.red) {
      ak("AK5", 1);
    } else {
      int rc = JOptionPane.showOptionDialog(null,
      "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
      JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
      options[1]);
      if (rc == 0) {
        ak("AK5", 0);
      }
    }
  }
  }//GEN-LAST:event_jButton2MouseClicked

  private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
    if (evt.isMetaDown()) {
      if (jButton3.getBackground() == Color.red) {
        ak("AK6", 1);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK6", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton3MouseClicked

  private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
    if (evt.isMetaDown()) {
      if (jButton4.getBackground() == Color.red) {
        ak("AK7", 1);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK7", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton4MouseClicked

  private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
    if (evt.isMetaDown()) {
      if (jButton5.getBackground() == Color.red) {
        ak("AK1", 1);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK1", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton5MouseClicked

  private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
    if (evt.isMetaDown()) {
      if (jButton6.getBackground() == Color.red) {
        ak("AK2", 1);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK2", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton6MouseClicked

  private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
    if (evt.isMetaDown()) {
      if (jButton7.getBackground() == Color.red) {
        ak("AK3", 1);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK3", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton7MouseClicked

  private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
    if (evt.isMetaDown()) {
      if (jButton8.getBackground() == Color.red) {
        ak("AK4", 1);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK4", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton8MouseClicked

  private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
    if (evt.isMetaDown()) {
      if (jButton9.getBackground() == Color.red) {
        ak("AK5", 2);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK5", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton9MouseClicked

  private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
    if (evt.isMetaDown()) {
      if (jButton10.getBackground() == Color.red) {
        ak("AK5", 2);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK6", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton10MouseClicked

  private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
    if (evt.isMetaDown()) {
      if (jButton11.getBackground() == Color.red) {
        ak("AK7", 2);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK7", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton11MouseClicked

  private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
    if (evt.isMetaDown()) {
      if (jButton12.getBackground() == Color.red) {
        ak("AK1", 2);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK1", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton12MouseClicked

  private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
    if (evt.isMetaDown()) {
      if (jButton13.getBackground() == Color.red) {
        ak("AK2", 2);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK2", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton13MouseClicked

  private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
    if (evt.isMetaDown()) {
      if (jButton14.getBackground() == Color.red) {
        ak("AK3", 2);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK3", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton14MouseClicked

  private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
    if (evt.isMetaDown()) {
      if (jButton15.getBackground() == Color.red) {
        ak("AK4", 2);
      } else {
        int rc = JOptionPane.showOptionDialog(null,
        "Przeka¿nik nie pod³¹czony do odp³ywu. Kontynuowaæ?", "",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options,
        options[1]);
        if (rc == 0) {
          ak("AK4", 0);
        }
      }
    }
  }//GEN-LAST:event_jButton15MouseClicked

  private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
    int i = jComboBox6.getSelectedIndex();
    JDialog jMC;
    if (i == 0) {
      jMC = new Parametry(this, true, 2);
    } else {
      jMC = new Charakterystyki(this, true, 2);
    }
    jMC.setVisible(true);
  }//GEN-LAST:event_jComboBox6ActionPerformed

  private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
    JDialog jfSek = new Sekwencje(this, true, sekwencje, sekwT);
    jfSek.validate();
    jfSek.setVisible(true);
  }//GEN-LAST:event_jButton32ActionPerformed

  private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
    JDialog jfSter = new SterowaniaPp(this, true, 1);
    jfSter.setVisible(true);
    // zapis do roznych odplywow
  }//GEN-LAST:event_jButton33ActionPerformed

  private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
    JDialog jfSter = new SterowaniaPp(this, true, 2);
    jfSter.setVisible(true);
    // zapis do roznych odplywow
  }//GEN-LAST:event_jButton34ActionPerformed

  private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
    JDialog jfSek = new Sekwencje(this, true, sekwencje, sekwT);
    jfSek.validate();
    jfSek.setVisible(true);

  }//GEN-LAST:event_jButton35ActionPerformed

  private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
    if (evt.isMetaDown()) {
      if (jButton16.getBackground() == Color.red) {
        JDialog jfRx = new Rx(this, true, 1, 1);
//        JFrame jfRx = new Rx(this, true, 1, 1);
        jfRx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton16MouseClicked

  private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
    if (evt.isMetaDown()) {
      if (jButton17.getBackground() == Color.red) {
        JDialog jfRx = new Rx(this, true, 2, 1);
        jfRx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton17MouseClicked

  private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
    if (evt.isMetaDown()) {
      if (jButton18.getBackground() == Color.red) {
        JDialog jfRx = new Rx(this, true, 3, 1);
        jfRx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton18MouseClicked

  private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
    if (evt.isMetaDown()) {
      if (jButton19.getBackground() == Color.red) {
        JDialog jfRx = new Rx(this, true, 4, 1);
        jfRx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton19MouseClicked

  private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
    if (evt.isMetaDown()) {
      if (jButton20.getBackground() == Color.red) {
        JDialog jfRx = new Rx(this, true, 1, 2);
        jfRx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton20MouseClicked

  private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
    if (evt.isMetaDown()) {
      if (jButton21.getBackground() == Color.red) {
        JDialog jfRx = new Rx(this, true, 2, 2);
        jfRx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton21MouseClicked

  private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
    if (evt.isMetaDown()) {
      if (jButton22.getBackground() == Color.red) {
        JDialog jfRx = new Rx(this, true, 3, 2);
        jfRx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton22MouseClicked

  private void jButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseClicked
    if (evt.isMetaDown()) {
      if (jButton23.getBackground() == Color.red) {
        JDialog jfRx = new Rx(this, true, 4, 2);
        jfRx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton23MouseClicked

  private void jButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseClicked
    if (evt.isMetaDown()) {
      if (jButton24.getBackground() == Color.red) {
        JDialog jfZx = new Zewx(this, true, 1, 1);
        jfZx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton24MouseClicked

  private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseClicked
    if (evt.isMetaDown()) {
      if (jButton25.getBackground() == Color.red) {
        JDialog jfZx = new Zewx(this, true, 2, 1);
        jfZx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton25MouseClicked

  private void jButton27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseClicked
    if (evt.isMetaDown()) {
      if (jButton27.getBackground() == Color.red) {
        JDialog jfZx = new Zewx(this, true, 4, 1);
        jfZx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton27MouseClicked

  private void jButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseClicked
    if (evt.isMetaDown()) {
      if (jButton28.getBackground() == Color.red) {
        JDialog jfZx = new Zewx(this, true, 1, 2);
        jfZx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton28MouseClicked

  private void jButton29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton29MouseClicked
    if (evt.isMetaDown()) {
      if (jButton29.getBackground() == Color.red) {
        JDialog jfZx = new Zewx(this, true, 2, 2);
        jfZx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton29MouseClicked

  private void jButton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseClicked
    if (evt.isMetaDown()) {
      if (jButton30.getBackground() == Color.red) {
        JDialog jfZx = new Zewx(this, true, 3, 2);
        jfZx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton30MouseClicked

  private void jButton31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton31MouseClicked
    if (evt.isMetaDown()) {
      if (jButton31.getBackground() == Color.red) {
        JDialog jfZx = new Zewx(this, true, 4, 2);
        jfZx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton31MouseClicked

  private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    JDialog jfIx = new Ix(this, true, 1, 1);
    jfIx.setVisible(true);
  }//GEN-LAST:event_jLabel1MouseClicked

  private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    JDialog jfIx = new Ix(this, true, 2, 2);
    jfIx.setVisible(true);
  }//GEN-LAST:event_jLabel2MouseClicked

  private void jButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseClicked
    if (evt.isMetaDown()) {
      if (jButton26.getBackground() == Color.red) {
        JDialog jfZx = new Zewx(this, true, 3, 1);
        jfZx.setVisible(true);
      } else {
        JOptionPane.showMessageDialog(null,
        "Element nie pod³¹czony do odp³ywu");
      }
    }
  }//GEN-LAST:event_jButton26MouseClicked
  public synchronized static boolean odzipuj(File file) {
    if (file == null || !file.exists() || !file.isFile()) {
      return false;
    }
    boolean fl = false;
    try {
      ZipInputStream zis = new ZipInputStream(new BufferedInputStream(
      new CheckedInputStream(new FileInputStream(file), new Adler32())));
      ZipEntry entry;
      while ((entry = zis.getNextEntry()) != null) {
        String ename = file.getParent() + File.separator + entry.getName();
        if (!ename.endsWith("nastaw.xls")) {
          continue;
        }
        File newFile = new File("nastaw.prop");
        if (entry.isDirectory()) {
          if (!newFile.mkdirs()) {
            break;
          }
          continue;
        }
        BufferedOutputStream bos = new BufferedOutputStream(
        new FileOutputStream(newFile));
        byte[] data = new byte[8192];
        int c;
        while ((c = zis.read(data)) != -1) {
          bos.write(data, 0, c);
          fl = true;
        }
        bos.flush();
        bos.close();
        zis.closeEntry();
        break;
      }
      zis.close();
    } catch (Exception ex) {
      fl = false;
    }
    return fl;
  }

  private Integer[] akxColorOd1() {
    Integer[] akx = new Integer[7];
    akx[0] = jButton2.getBackground() == Color.red ? 1 : 0;
    akx[1] = jButton3.getBackground() == Color.red ? 1 : 0;
    akx[2] = jButton4.getBackground() == Color.red ? 1 : 0;
    akx[3] = jButton5.getBackground() == Color.red ? 1 : 0;
    akx[4] = jButton6.getBackground() == Color.red ? 1 : 0;
    akx[5] = jButton7.getBackground() == Color.red ? 1 : 0;
    akx[6] = jButton8.getBackground() == Color.red ? 1 : 0;
    return akx;
  }

  private Integer[] akxColorOd2() {
    Integer[] akx = new Integer[7];
    akx[0] = jButton9.getBackground() == Color.red ? 1 : 0;
    akx[1] = jButton10.getBackground() == Color.red ? 1 : 0;
    akx[2] = jButton11.getBackground() == Color.red ? 1 : 0;
    akx[3] = jButton12.getBackground() == Color.red ? 1 : 0;
    akx[4] = jButton13.getBackground() == Color.red ? 1 : 0;
    akx[5] = jButton14.getBackground() == Color.red ? 1 : 0;
    akx[6] = jButton15.getBackground() == Color.red ? 1 : 0;
    return akx;
  }

  private void createBuff() {
    Okno.strAKx = new StringBuffer[7];
    Okno.strAKKom = new StringBuffer[7];
    Okno.strRx = new StringBuffer[4];
    for (int i = 0; i < 7; i++) {
      if (Okno.strAKx[i] == null) {
        Okno.strAKx[i] = new StringBuffer();
      }
      if (Okno.strAKKom[i] == null) {
        Okno.strAKKom[i] = new StringBuffer();
      }
    }
    for (int i = 0; i < 4; i++) {
      if (Okno.strRx[i] == null) {
        Okno.strRx[i] = new StringBuffer();
      }
    }
    if (data == null || data.length == 0){
      JOptionPane.showMessageDialog(null, "brak danych AK");
      return;
    }
    for (int i = 0; i < data.length; i++){
      Okno.strAKx[0].append((boolean)data[i][6] ? 1:0);
      Okno.strAKx[1].append((boolean)data[i][7] ? 1:0);
      Okno.strAKx[2].append((boolean)data[i][8] ? 1:0);
      Okno.strAKx[3].append((boolean)data[i][9] ? 1:0);
      Okno.strAKx[4].append((boolean)data[i][10] ? 1:0);
      Okno.strAKx[5].append((boolean)data[i][11] ? 1:0);
      Okno.strAKx[6].append((boolean)data[i][12] ? 1:0);
    }
    for (int i = 0; i < akxKom.length; i++){
      Okno.strAKKom[0].append(akxKom[i][0].trim()).append("\n");
      Okno.strAKKom[1].append(akxKom[i][1].trim()).append("\n");
      Okno.strAKKom[2].append(akxKom[i][2].trim()).append("\n");
      Okno.strAKKom[3].append(akxKom[i][3].trim()).append("\n");
      Okno.strAKKom[4].append(akxKom[i][4].trim()).append("\n");
      Okno.strAKKom[5].append(akxKom[i][5].trim()).append("\n");
      Okno.strAKKom[6].append(akxKom[i][6].trim()).append("\n");
    }
    if (rx == null || rx.length == 0){
      JOptionPane.showMessageDialog(null, "brak danych Rx");
      return;
    }
    for (int i = 0; i < rx.length; i++){
      String str = "";
      if (!rx[i][4].toString().equals("X")){
        str = rx[i][4].toString();
        JComboBox jb = Rx.bx1;
        for (int j = 0; j < jb.getItemCount(); j++){
          if (u.extractText(jb.getItemAt(j).toString()).equals(str)){
            str=Integer.toString(j);
          }
        }
      }
      
      if (rx[i][0] instanceof Boolean){
        str = (boolean)rx[i][0] ? "1":"0";
      } else if (rx[i][0] instanceof Float){
        str = Float.toString((float) rx[i][0]);
    }
      Okno.strRx[0].append(str).append("\n");
    }
  }

  /**
   * @param args the command line arguments
   */

// Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton11;
  private javax.swing.JButton jButton12;
  private javax.swing.JButton jButton13;
  private javax.swing.JButton jButton14;
  private javax.swing.JButton jButton15;
  private javax.swing.JButton jButton16;
  private javax.swing.JButton jButton17;
  private javax.swing.JButton jButton18;
  private javax.swing.JButton jButton19;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton20;
  private javax.swing.JButton jButton21;
  private javax.swing.JButton jButton22;
  private javax.swing.JButton jButton23;
  private javax.swing.JButton jButton24;
  private javax.swing.JButton jButton25;
  private javax.swing.JButton jButton26;
  private javax.swing.JButton jButton27;
  private javax.swing.JButton jButton28;
  private javax.swing.JButton jButton29;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton30;
  private javax.swing.JButton jButton31;
  private javax.swing.JButton jButton32;
  private javax.swing.JButton jButton33;
  private javax.swing.JButton jButton34;
  private javax.swing.JButton jButton35;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  private javax.swing.JComboBox<String> jComboBox3;
  private javax.swing.JComboBox<String> jComboBox6;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel10;
  private javax.swing.JPanel jPanel11;
  private javax.swing.JPanel jPanel12;
  private javax.swing.JPanel jPanel13;
  private javax.swing.JPanel jPanel16;
  private javax.swing.JPanel jPanel17;
  private javax.swing.JPanel jPanel19;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
// End of variables declaration//GEN-END:variables
}
